#ifndef CONSTANT_H
#define CONSTANT_H

#define NO_PREDEFINED -1

#define MAX_BIND_VARIABLES 32768
#define MAX_EXCEPTION_HANDLERS 65536
#define MAX_FIELDS_IN_A_RECORD 65536
#define LEVELS_BLOCK_NESTING 255
#define LEVELS_RECORD_NESTING 32
#define LEVELS_SUBQUERY_NESTING 254
#define LEVELS_LABEL_NESTING 98
#define LEVELS_NESTED_COLLECTIONS NO_PREDEFINED
#define MAGNITUDE_PLS_INTEGER_BINARY_INTEGER INT_MAX // 4 bytes integer
#endif
